### ISSUE TITLE
Is pip2 still necessary?

### ISSUE THREAD

**Issue by Folaht** [cznweb/arkos#18]
```log
2017-01-22 09:59:03,968 [R] [[37mDEBUG[0m  ] Apps: Getting system/python/ruby installed list
Traceback (most recent call last):
  File "/home/folatt/.eclipse/org.eclipse.platform_4.6.2_155965261_linux_gtk_x86_64/plugins/org.python.pydev_5.4.0.201611281236/pysrc/pydevd.py", line 1537, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/folatt/.eclipse/org.eclipse.platform_4.6.2_155965261_linux_gtk_x86_64/plugins/org.python.pydev_5.4.0.201611281236/pysrc/pydevd.py", line 976, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/folatt/.eclipse/org.eclipse.platform_4.6.2_155965261_linux_gtk_x86_64/plugins/org.python.pydev_5.4.0.201611281236/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/folatt/workspace/arkos/kraken/krakend", line 93, in <module>
    environment,  config_file, secrets_file, policy_file, debug
  File "/home/folatt/workspace/arkos/kraken/kraken/application.py", line 95, in run_daemon
    arkos.initial_scans()
  File "/home/folatt/workspace/arkos/core/arkos/__init__.py", line 90, in initial_scans
    applications.scan(cry=False)
  File "/home/folatt/workspace/arkos/core/arkos/applications.py", line 459, in scan
    "py2": python.get_installed(py2=True),
  File "/home/folatt/workspace/arkos/core/arkos/languages/python.py", line 67, in get_installed
    s = shell("pip{0} freeze".format("2" if py2 else ""))
  File "/home/folatt/workspace/arkos/core/arkos/utilities/utils.py", line 250, in shell
    env=environ)
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pip2'
```

**Comment by peakwinter** [comment]
If I recall correctly it's only ever used for Mailpile.

**Comment by peakwinter** [comment]
This is confirmed to be true. We will keep this functionality at least until Mailpile updates to 3.x +, see mailpile/Mailpile#160
