### ISSUE TITLE
Can't run ArchLinux install script (missing mirrors)

### ISSUE THREAD

**Issue by pomarec** [cznweb/arkos#19]
In [this tutorial](https://arkos.io/download/#arch-convert) the [script for ArchLinux install](https://pkg.arkos.io/resources/install_arch.py) references a [mirror list](https://pkg.arkos.io/resources/arkos-mirrorlist-latest.pkg.tar.xz) at `line 94` that no longer exists. It results in the following error:

```
# curl -s https://pkg.arkos.io/resources/install_arch.py | python
=== arkOS ===
Arch-to-arkOS Conversion Script

Using this script will convert your Arch Linux installation to a fully-functional arkOS server. It will irreversibly alter the software configurations on your machine. You should make no assumptions about your ability to manually
configure your server after this script has successfully completed, except by using the tools and methods included in arkOS.

If you do NOT want this to occur, press Ctrl+C now.
Installing in 8....
Installing in 1...
Installing new packages...
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key B0B8CA6131F90C40 marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/4F88CC230F0148D38DB23B4EB0B8CA6131F90C40.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: key 0155ED1E0585F850: public key "Jacob Cook (arkOS Package Signing) <jacob@citizenweb.io>" imported
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Total number processed: 1
gpg:               imported: 1
==> Updating trust database...
gpg: no need for a trustdb check
  -> Locally signing key 0585F850...
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   1  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2019-03-21
:: Starting full system upgrade...
 there is nothing to do
error: package 'arkos-mirrorlist' was not found
Traceback (most recent call last):
  File "<stdin>", line 174, in <module>
  File "<stdin>", line 95, in install
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by peakwinter** [comment]
Thanks for pointing out the issue! The softlink got squashed when we moved servers last week. This has been fixed.
