### ISSUE TITLE
Dependencies installation

### ISSUE THREAD

**Issue by pomarec** [cznweb/arkos#23]
When i create a virtualenv and install arkos-core it does not install some dependencies correctly (pycryptsetup & pyparted).

```
pip install -e git+https://github.com/arkoscloud/core.git#egg=arkosctl
Obtaining arkosctl from git+https://github.com/arkoscloud/core.git#egg=arkosctl
  git clone in ./.venv/src/arkosctl exists with URL https://github.com/pomarec/core.git
  Cloning https://github.com/arkoscloud/core.git to ./.venv/src/arkosctl
  Running setup.py (path:/home/deploy/test/.venv/src/arkosctl/setup.py) egg_info for package arkosctl produced metadata for project name arkos-core. Fix your #egg=arkosctl fragments.
Collecting click (from arkos-core)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting cryptography (from arkos-core)
  Using cached cryptography-1.7.2.tar.gz
Collecting dbus-python (from arkos-core)
  Using cached dbus-python-1.2.4.tar.gz
Collecting free_tls_certificates (from arkos-core)
  Using cached free_tls_certificates-0.1.6.tar.gz
Collecting GitPython (from arkos-core)
  Using cached GitPython-2.1.1-py2.py3-none-any.whl
Collecting gnupg (from arkos-core)
  Using cached gnupg-2.2.0-py3-none-any.whl
Collecting miniupnpc (from arkos-core)
  Using cached miniupnpc-1.9.tar.gz
Collecting netifaces (from arkos-core)
  Using cached netifaces-0.10.5.tar.gz
Collecting ntplib (from arkos-core)
  Using cached ntplib-0.3.3.tar.gz
Collecting psutil (from arkos-core)
  Using cached psutil-5.0.1.tar.gz
Collecting pyldap (from arkos-core)
  Using cached pyldap-2.4.28.tar.gz
Requirement already satisfied: pyparted==3.10.7 in ./.venv/lib/python3.6/site-packages (from arkos-core)
Collecting pycryptsetup==1.7.2 (from arkos-core)
  Could not find a version that satisfies the requirement pycryptsetup==1.7.2 (from arkos-core) (from versions: )
No matching distribution found for pycryptsetup==1.7.2 (from arkos-core)
```

**Comment by pomarec** [comment]
My investigation lead me to understand few things :
- you should use `--process-dependency-links` with the `pip install`
- BUT this feature is deprecated as we speak and is in process for being put back in pip

Links :
- https://github.com/pypa/pip/pull/1955
- http://stackoverflow.com/questions/12518499/pip-ignores-dependency-links-in-setup-py
- https://groups.google.com/forum/#!topic/pypa-dev/tJ6HHPQpyJ4

**Comment by pomarec** [comment]
Cloning the repo and running `python setup.py install` works but then we miss some dependencies :
```
 arkosctl
Traceback (most recent call last):
  File "/home/deploy/test/.venv/bin/arkosctl", line 3, in <module>
    from arkos.ctl import cli
  File "/home/deploy/test/.venv/lib/python3.6/site-packages/arkos_core-0.8.3-py3.6.egg/arkos/__init__.py", line 15, in <module>
    from arkos.connections import ConnectionsManager
  File "/home/deploy/test/.venv/lib/python3.6/site-packages/arkos_core-0.8.3-py3.6.egg/arkos/connections.py", line 16, in <module>
    from dbus import SystemBus, Interface
ModuleNotFoundError: No module named 'dbus'
```

```
pip install dbus-python
Requirement already satisfied: dbus-python in /home/deploy/test/.venv/lib/python3.6/site-packages/dbus_python-1.2.4-py3.6-linux-armv7l.egg
```

**Comment by peakwinter** [comment]
Yeah, the distribution of modules that are forked or otherwise not available on PyPI is not optimal at the moment. It's not clear what the preferred way of `setuptools` is to handle this issue, either. Needs more research!
